### Computer Science: Computing inverse of a matrix by the cofactor matrix in Python
$A^{-1}=\frac{C^{T}}{det(A)}$
###### by Hamed Shah-Hosseini
Explanation at: https://www.pinterest.com/HamedShahHosseini/
<br>https://github.com/ostad-ai/Computer-Science

In [2]:
import numpy as np

In [108]:
#-- This was introduced in an earlier post
#--Computing determinant by converting 
#--the matrix C to to an upper triangular one
def det(C):
    A=C.copy().astype('float64')
    n=A.shape[0]
    signChange=1
    for ii in range(n-1):
        if A[ii,ii]==0:
            flag=False
            for j in range(ii+1,n):
                if A[j,ii]!=0:
                    A[ii],A[j]=A[j].copy(),A[ii].copy()
                    flag=True; signChange*=-1
                    break 
            if flag is False:
                continue
        for j in range(ii+1,n):
            if A[j,ii]!=0:
                landa=A[j,ii]/A[ii,ii]
                A[j,ii:]=A[j,ii:]-landa*A[ii,ii:]
    product=signChange
    for ii in range(n):
        product*=A[ii,ii]
    return product,A

In [118]:
# Computes the cofactor matrix
def cofactor_matrix(A):
    detA=det(A)[0]
    if detA==0: # it is singular 
        return None
    n=A.shape[0]
    C=np.zeros_like(A).astype('float')
    for i in range(n):
        for j in range(n):
            rx=list(range(i))+list(range(i+1,n))
            ry=list(range(j))+list(range(j+1,n))
            Aij=A[np.ix_(rx,ry)]
            C[i,j]=((-1)**(i+j))*det(Aij)[0]
    return C

# Getting the inverse
def inverse_matrix(A):
    detA=det(A)[0]
    if detA==0: # it is singular 
        return None
    return cofactor_matrix(A).T/detA

In [110]:
# Example: we get the inverse
m=np.array(np.random.randint(2,5,25)).reshape(5,5)
m_inv=inverse_matrix(m)
if m_inv is not None:
    # we check if (m_inv*m) is Identity or not
    print('m_inv*m==I?',
    np.allclose(np.dot(m_inv,m),np.eye(m.shape[0])))

m_inv*m==I? True


In [111]:
# Rounding the values up to 10 decimals
print(np.round(np.dot(m_inv,m),10))

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [-0. -0. -0.  1. -0.]
 [-0. -0. -0. -0.  1.]]


In [115]:
print('The matrix:\n',m)
print('The inverse of matrix:\n',m_inv)

The matrix:
 [[3 2 4 4 3]
 [4 3 2 2 3]
 [3 3 4 4 3]
 [3 4 3 2 3]
 [2 3 4 4 2]]
The inverse of matrix:
 [[ 1.5   1.   -3.5  -0.    1.5 ]
 [-1.    0.    1.    0.    0.  ]
 [ 2.5   0.   -4.5   1.    1.5 ]
 [-1.75 -0.    3.25 -1.   -0.75]
 [-1.5  -1.    4.5  -0.   -2.5 ]]
