# Computer Science
## Determinant of a square matrix
For a *square* matrix $A$, its **determinant**,denoted by $det(A)$ or $|A|$ is a scalar value, which reflects some properties of the given matrix. In the following, several properties of the determinant are mentioned ($A$ and $B$ are square matrices):
<br>
- $|I|=1$, where $I$ is the identity matrix
- $|A|=\prod_i a_{ii}$, where $A$ is a triangular matrix
- $|A^T|=|A|$
- $|AB|=|BA|=|A||B|$, where $A$ and $B$ are of the same size.
- $|cA|=c^n|A|$
- $|A^-1|=\frac{1}{|A|}$, $|A|\ne0$
- $|A|=\prod_i \lambda_i$ where $\lambda_i$ are the eigenvalues of matrix $A$

In the examples below, some properties of determinant are checked in Python code. Also, the function to compute **cofactors** and **minors** of the matrix are expressed. 
<br>**Hint:** It should be noted that we earlier provided a notebook file in this *repository* to implement computing determinant from scratch, for those interested to implement algorithms from scratch.
<br> The **Python** code is at: https://github.com/ostad-ai/Computer-Science
<br> Explanation in **English** at: https://www.pinterest.com/HamedShahHosseini/computer-science/background-knowledge/

In [1]:
# import required modules
import numpy as np

In [2]:
# example
n=3 # size of square matrices
# the matrices
A=np.random.randint(1,10,(n,n))
B=np.random.randint(1,10,(n,n))
print(f'-----The matrix A is:\n{A} ')
print(f'-----The determinant of matrix A:',np.linalg.det(A))
print(f'-----The determiant of matrix A.T: {np.linalg.det(A.T)}')
print(f'1/det(A): {1/np.linalg.det(A)}')
print(f'det(A^-1): {np.linalg.det(np.linalg.inv(A))}')
#relation of determinant with eigenvalues
eigs=np.linalg.eigvals(A)
print(f'-----The multiplication of eigenvalues of the matrix A:{np.prod(eigs)}')
#cheching the commutativity of trace
print(f'det(A*B): {np.linalg.det(A@B)}')
print(f'det(B*A): {np.linalg.det(B@A)}')
print(f'det(A)*det(B): {np.linalg.det(A)*np.linalg.det(B)}')

-----The matrix A is:
[[8 2 6]
 [6 6 5]
 [4 8 7]] 
-----The determinant of matrix A: 115.99999999999989
-----The determiant of matrix A.T: 115.99999999999999
1/det(A): 0.008620689655172422
det(A^-1): 0.008620689655172422
-----The multiplication of eigenvalues of the matrix A:(115.99999999999997+0j)
det(A*B): -9743.999999999953
det(B*A): -9744.000000000005
det(A)*det(B): -9743.999999999989


In [19]:
# example on minors and cofactor
# matrix A is square
#returns both minor matrix and cofactor matrix
def minor_cofactor(A):
    n=A.shape[0]
    C=np.zeros((n,n))
    M=C.copy()
    for i in range(n):
        for j in range(n):
            M[i,j]=np.linalg.det(np.delete(np.delete(A,i,0),j,1))
            C[i,j]=(-1)**(i+j)*M[i,j]
    return M,C

In [29]:
# example of cofactor to compute determinant and inverse
M,C=minor_cofactor(A)
row=2
detA=np.sum(A[row]*C[row])
print(f'det(A) by cofactor: {detA}')
print('-----------')
adjA=C.T # adjugate of matrix A
A_inv=adjA/detA
print(f'-----inverse of matrix A by its adjugate:\n {A_inv}')
print(f'-----checking A*A_inverse=I:\n {A@A_inv}')

det(A) by cofactor: 116.0
-----------
-----inverse of matrix A by its adjugate:
 [[ 0.01724138  0.29310345 -0.22413793]
 [-0.18965517  0.27586207 -0.03448276]
 [ 0.20689655 -0.48275862  0.31034483]]
-----checking A*A_inverse=I:
 [[ 1.00000000e+00  6.66133815e-16 -1.11022302e-16]
 [-3.60822483e-16  1.00000000e+00 -1.66533454e-16]
 [-6.38378239e-16  5.55111512e-16  1.00000000e+00]]
