# Computer Science
## Trace of a square matrix
For a square matrix $A$, its trace is defined as the sum of the elements on the main diagonal of $A$:
<br>$trace(A)=\sum_i a_{ii}$
<br>For $trace$, we have several properties. Some of them are expressed below:
- $trace(A)=trace(A^T)$
- $trace(AB)=trace(BA)$
- $trace(A+B)=trace(A)+trace(B)$
- $trace(cA)=ctrace(A)$
- $trace(A)=\sum_i \lambda_i$ where $\lambda_i$ are the eigenvalues of matrix $A$
- $trace(A^TB)=trace(AB^T)=trace(B^TA)=trace(BA^T)$

In the following, we demonstrate some properties mentioned above by examples in Python code. Aso, we provide a trace function from scratch.
<br> The **Python** code is at: https://github.com/ostad-ai/Computer-Science
<br> Explanation in **English** at: https://www.pinterest.com/HamedShahHosseini/computer-science/background-knowledge/

In [1]:
# import required modules
import numpy as np

In [2]:
# example
# the matrices
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[-1,-2,-3],[-4,-5,-6],[-7,-8,-9]])
print(f'-----The matrix A is:\n{A} ')
print(f'-----The trace of matrix A:',np.trace(A))
#relation of trace with eigenvalues
eigs=np.linalg.eigvals(A)
print(f'-----The sum of eigenvalues of the matrix A:{np.sum(eigs)}')
print(f'-----The trace of matrix A.T: {np.trace(A.T)}')
#cheching the commutativity of trace
print(f'The trace of matrix A*B: {np.trace(A@B)}')
print(f'The trace of matrix B*A: {np.trace(B@A)}')
print('------------')
print(f'The trace of A.T*B: {np.trace(A.T@B)}')
print(f'The trace of A*B.T: {np.trace(A@B.T)}')
print(f'The trace of B*A.T: {np.trace(B@A.T)}')
print(f'The trace of B.T*A: {np.trace(B.T@A)}')

-----The matrix A is:
[[1 2 3]
 [4 5 6]
 [7 8 9]] 
-----The trace of matrix A: 15
-----The sum of eigenvalues of the matrix A:14.999999999999998
-----The trace of matrix A.T: 15
The trace of matrix A*B: -261
The trace of matrix B*A: -261
------------
The trace of A.T*B: -285
The trace of A*B.T: -285
The trace of B*A.T: -285
The trace of B.T*A: -285


In the following code, we implement the $trace$ from scratch

In [3]:
#implementing the trace of a square matrix from scratch:
def tr(A):
    n=A.shape[0]
    trA=0
    for i in range(n):
        trA+=A[i,i]
    return trA
print(f'The trace of matrix A by the function from scratch: {tr(A)} ')

The trace of matrix A by the function from scratch: 15 
