### Computer Science: Computing determinant of a matrix by converting it into an upper triangular one
###### by Hamed Shah-hosseini
Explanation at: https://www.pinterest.com/HamedShahHosseini/
<br>https://github.com/ostad-ai/Computer-Science

In [2]:
import numpy as np

In [4]:
#--Computing determinant by converting 
#--the matrix C to to an upper triangular one
def det(C):
    A=C.copy().astype('float64')
    n=A.shape[0]
    signChange=1
    for ii in range(n-1):
        if A[ii,ii]==0:
            flag=False
            for j in range(ii+1,n):
                if A[j,ii]!=0:
                    A[ii],A[j]=A[j].copy(),A[ii].copy()
                    flag=True; signChange*=-1
                    break 
            if flag is False:
                continue
        for j in range(ii+1,n):
            if A[j,ii]!=0:
                landa=A[j,ii]/A[ii,ii]
                A[j,ii:]=A[j,ii:]-landa*A[ii,ii:]
    product=signChange
    for ii in range(n):
        product*=A[ii,ii]
    return product,A

In [5]:
A=np.array([[0,2,3],
            [4,5,6],
            [7,8,9]],dtype=np.float64)
print('Determinant of Matrix with numpy: ',np.linalg.det(A))
print('Determinant of Matrix with  code: ',det(A)[0])

Determinant of Matrix with numpy:  3.000000000000001
Determinant of Matrix with  code:  3.0


In [6]:
A=np.random.rand(50,50)
print('Determinant of Matrix with numpy: ',np.linalg.det(A))
print('Determinant of Matrix with  code: ',det(A)[0])

Determinant of Matrix with numpy:  -26812.5707842879
Determinant of Matrix with  code:  -26812.57078429096


In [12]:
A=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]],dtype=np.float64)
detMat,upper=det(A)
print('Determinant of Matrix with  code: ',detMat)
print('Upper triangular matrix:\n',upper)

Determinant of Matrix with  code:  -0.0
Upper triangular matrix:
 [[ 1.  2.  3.]
 [ 0. -3. -6.]
 [ 0.  0.  0.]]
