### Computer Science: Computing inverse of a matrix by Gauss-Jordan elimination in Python
$[A|I] \rightarrow [I|A^{-1}]$
###### by Hamed Shah-Hosseini
Explanation in English: https://www.pinterest.com/HamedShahHosseini/
<br>Explanation in Persian: https://www.instagram.com/words.persian
<br> Python code at: https://github.com/ostad-ai/Computer-Science

In [4]:
import numpy as np

In [43]:
# to find inverse of a square matrix A
# A is changed in this implementation
def Gauss_Jordan(A):
    n=A.shape[0] #row size==column size
    I=np.identity(n)
    for i in range(n):
        # find maximum value in each column below the row
        i_max=i+np.argmax(np.abs(A[i:,i]))
        if A[i_max,i]==0: return None # no inverse
        elif i_max!=i:
            A[i,:],A[i_max,:]=A[i_max,:].copy(),A[i,:].copy()
            I[i,:],I[i_max,:]=I[i_max,:].copy(),I[i,:].copy()
        for j in range(n):
            if i==j: continue
            if A[j,i]==0: continue
            ratio=A[j,i]/A[i,i]
            for k in range(n):
                A[j,k]-=ratio*A[i,k]
                I[j,k]-=ratio*I[i,k]    
    for i in range(n):
        I[i,:]/=A[i,i]
        A[i,:]/=A[i,i]
    return I

In [46]:
n=5  # testing the Gauss-Jordan elimination
A=np.identity(n)+np.random.rand(n,n)
Ac=A.copy()
AInv=Gauss_Jordan(Ac)
print('Are the results accurate?',
      np.allclose(np.linalg.inv(A),AInv))
print("A_inverse * A:")
print(np.round(np.dot(AInv,A),5))

Are the results accurate? True
A_inverse * A:
[[ 1.  0.  0.  0. -0.]
 [-0.  1.  0. -0. -0.]
 [ 0.  0.  1.  0.  0.]
 [ 0. -0. -0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
